### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by MrTooOldDriver** [chineseiven/EDrouter#15]
`string[] logPath = Directory.GetFiles(logDir);`
如果用户从未运行过Elite Dangerous或本地数据不在
@"%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous"的话，会引起System.IO.DirectoryNotFoundException.

**Comment by nekomeowww** [comment]
那就写一个Try + Catch然后pass这个Exception

**Comment by MrTooOldDriver** [comment]
Project ShutDown
