### ISSUE TITLE
Math Issues About Spherical Coordinate System

### ISSUE THREAD

**Issue by MrTooOldDriver** [chineseiven/EDrouter#19]
目前算法中，校验路径点需要利用polar angle and azimuthal angle进行校验。
（待确认）目前算法中polar angle and azimuthal angle范围是 -180°-180°，所以需要一个 180°++要转换回 -180°++的步骤。

**Comment by nekomeowww** [comment]
emmm
能标注是哪段代码么我帮你看看

**Comment by MrTooOldDriver** [comment]
Project ShutDown
